version: "3"
services:
  node-app:
    build: 
      context: .
      target: dev
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - FRONTEND_URL=http://localhost:8080
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=luke
      - MONGO_INITDB_ROOT_PASSWORD=luke

    volumes:
      - mongo-db:/data/db

  redis:
    image: redis

volumes:
  mongo-db:
