version: "3"
services:
  node-app:
    build: 
      context: .
      target: prod
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis

volumes:
  mongo-db:
