version: "3"
services:
  node-app:
    build: 
      context: .
      target: prod
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    volumes:
      - mongo-db-prod:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=luke
      - MONGO_INITDB_ROOT_PASSWORD=luke

  redis:
    image: redis

volumes:
  mongo-db-prod:
